name: CreateUser build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.LDAP.CreateUser/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.LDAP.CreateUser
      prebuild_command: docker pull dwimberger/ldap-ad-it && docker run -i --rm -p 10389:10389 dwimberger/ldap-ad-it
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}