name: CreateUser build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.LDAP.CreateUser/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.LDAP.CreateUser
      prebuild_command: docker run --rm -p 10389:10389 dwimberger/ldap-ad-it
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}